// GENERATED by scripts/generate-privacy-policy.mjs — DO NOT EDIT BY HAND.
//
// Source of truth: privacy-policy-el.md (AUTHORITATIVE) and privacy-policy-en.md
// (for convenience). Edit those, then re-run the script.
//
// The "Internal notes" section of the EN file is excluded on purpose: it is a
// working checklist, not public policy.
//
// Generated: 2026-10-02
// Sections: en 10, gr 10

/** A table inside a policy section. */
export interface PolicyTable {
  headers: string[];
  rows: string[][];
}

/** A string is a paragraph, a string[] is a bulleted list, else a table. */
export type PolicyBlock = string | string[] | PolicyTable;

export interface PolicySection {
  id: string;
  heading: string;
  body: PolicyBlock[];
}

export interface PolicyDoc {
  metaTitle: string;
  metaDescription: string;
  title: string;
  lastUpdatedLabel: string;
  lastUpdated: string;
  pendingLabel: string;
  intro: PolicyBlock[];
  sections: PolicySection[];
  contactLine: string;
}

export const privacyPolicy: Record<"en" | "gr", PolicyDoc> = {
  "en": {
    "metaTitle": "Privacy Policy | Movability",
    "metaDescription": "How Movability (KOINIS IKE) collects, uses and retains your personal data when you rent mobility equipment in Athens.",
    "lastUpdatedLabel": "Last updated",
    "pendingLabel": "Pending",
    "contactLine": "Questions about this policy? Email us at",
    "title": "Privacy Policy",
    "lastUpdated": "2 October 2026",
    "intro": [],
    "sections": [
      {
        "id": "1",
        "heading": "1. Who we are",
        "body": [
          "Movability (movability.gr) rents mobility equipment in Athens, Greece. The service is operated by KOINIS IKE, VAT No EL999050083, Ipsilantou 22, 17778 Tavros, Attiki, Greece. We are the controller of the personal data described in this policy.",
          "For any privacy question or request, write to info@movability.gr.",
          "This policy covers our website, bookings, customer accounts, the AI chat assistant, and our email and WhatsApp communication with you."
        ]
      },
      {
        "id": "2",
        "heading": "2. What personal data we collect",
        "body": [
          "We collect only what we need to rent you equipment, deliver it and answer your questions.",
          {
            "headers": [
              "When you",
              "What we collect"
            ],
            "rows": [
              [
                "Make a booking",
                "Name, email, phone number (including your WhatsApp number), delivery address or hotel name, rental dates, delivery time slot, delivery notes, the equipment booked, amounts paid, and any special requirements you choose to write"
              ],
              [
                "Create an account (optional)",
                "Name, email, phone number, and a password (stored only as a one-way hash) or your Google sign-in identifier"
              ],
              [
                "Pay",
                "Card payments are handled by Stripe. We never see or store your card number. We keep the payment status, amounts and Stripe payment references"
              ],
              [
                "Contact us or send a partner enquiry",
                "Name, email, phone number, subject and message"
              ],
              [
                "Chat with our AI assistant",
                "The messages you type, the language, your browser's user-agent text, a salted one-way hash of your IP address (not the IP address itself) and timestamps"
              ],
              [
                "Message us on WhatsApp or by phone",
                "Your number and the content of the conversation"
              ],
              [
                "Browse the site",
                "Cookies and analytics data, as described in section 8"
              ]
            ]
          },
          "We also send you automated emails: booking confirmations, a review request after your rental, and a single reminder if you start a booking but do not complete payment.",
          "**Health information.** The special requirements and delivery notes fields are optional free text. You do not need to tell us a diagnosis — describing your functional needs (for example \"step-free access\" or \"narrow doorways\") is enough for us to bring the right equipment. If you choose to provide information about your health or a disability, we ask for your explicit consent at the point you provide it, and we process that information solely to arrange and fulfil your rental. We never use it for marketing. You can withdraw your consent at any time at info@movability.gr; withdrawal does not affect processing already lawfully carried out before it.",
          "We do not sell personal data."
        ]
      },
      {
        "id": "3",
        "heading": "3. Why we use your data, and the legal basis",
        "body": [
          {
            "headers": [
              "Purpose",
              "Legal basis (GDPR)"
            ],
            "rows": [
              [
                "Take your booking, deliver and collect the equipment, take payment, return your security deposit",
                "Contract, Art. 6(1)(b)"
              ],
              [
                "Send booking confirmations and delivery or collection updates",
                "Contract, Art. 6(1)(b)"
              ],
              [
                "Create and operate your optional customer account (sign-in and authentication)",
                "Contract, Art. 6(1)(b)"
              ],
              [
                "Answer your questions and partner enquiries by form, email, WhatsApp, phone or chat",
                "Contract (if you are booking) or our legitimate interest in responding to people who contact us, Art. 6(1)(f)"
              ],
              [
                "Keep accounting and tax records",
                "Legal obligation, Art. 6(1)(c)"
              ],
              [
                "Remind you once about a booking you started but did not complete",
                "Our legitimate interest in helping you complete a booking you began, Art. 6(1)(f), where permitted under applicable electronic-communications law. Every such email contains an opt-out, and you can object at any time"
              ],
              [
                "Ask for a review after your rental",
                "Our legitimate interest in understanding and improving our service, Art. 6(1)(f). Every such email contains an opt-out, and you can object at any time"
              ],
              [
                "Run the AI chat assistant",
                "Our legitimate interest in answering visitors' questions and preventing fraudulent or abusive use of the website, Art. 6(1)(f)"
              ],
              [
                "Secure the site and prevent fraud",
                "Our legitimate interest in preventing fraudulent or abusive use of the website, Art. 6(1)(f)"
              ],
              [
                "Website analytics cookies",
                "Your consent, Art. 6(1)(a)"
              ],
              [
                "Health information you choose to provide",
                "Your explicit consent, Art. 9(2)(a)"
              ]
            ]
          }
        ]
      },
      {
        "id": "4",
        "heading": "4. Who we share it with",
        "body": [
          "We share personal data with the service providers and other recipients below. Depending on the service and the processing activity, they may act as processors on our instructions or as separate controllers. Our own delivery team and staff see only what they need (name, phone, address, equipment).",
          {
            "headers": [
              "Provider",
              "What it does for us",
              "Your data it handles"
            ],
            "rows": [
              [
                "Supabase",
                "Database, sign-in, file storage and server functions",
                "Bookings, accounts, enquiries, chat conversations"
              ],
              [
                "Vercel",
                "Hosts the website",
                "Technical request data"
              ],
              [
                "Stripe",
                "Card payments",
                "Payment details, name, email, amount"
              ],
              [
                "Resend",
                "Sends our emails",
                "Email address, name, email content"
              ],
              [
                "Google",
                "Analytics (with your consent), Google sign-in",
                "Analytics data, sign-in identifier"
              ],
              [
                "Anthropic",
                "Provides the AI model behind the chat assistant",
                "The text of your chat messages"
              ],
              [
                "WhatsApp (Meta)",
                "Messaging, when you choose to message us",
                "Your number and the conversation"
              ]
            ]
          },
          "We may also disclose data to our accountant and to authorities where the law requires it.",
          "If you post a review on Google, that review is published by Google under Google's own policy, not ours."
        ]
      },
      {
        "id": "5",
        "heading": "5. Transfers outside the EU/EEA",
        "body": [
          "Some of our providers are based in the United States or process data there. When your data leaves the EU/EEA we rely on an EU adequacy decision (such as the EU-US Data Privacy Framework for certified providers) or on Standard Contractual Clauses. You can ask us for a copy of the safeguards at info@movability.gr."
        ]
      },
      {
        "id": "6",
        "heading": "6. How long we keep data",
        "body": [
          {
            "headers": [
              "Data",
              "How long"
            ],
            "rows": [
              [
                "AI chat conversations",
                "90 days, then deleted automatically"
              ],
              [
                "Booking and payment records required for accounting and tax",
                "5 years from the end of the year in which the related tax-filing obligation arises, or longer where the tax assessment period remains open, an audit or dispute is ongoing, or another legal rule requires it"
              ],
              [
                "Operational booking details (delivery notes, addresses, time slots)",
                "2 years after the rental ends"
              ],
              [
                "Health information you provided for a booking",
                "60 days after the rental ends"
              ],
              [
                "Contact and partner enquiries",
                "2 years"
              ],
              [
                "Bookings started but not paid",
                "6 months"
              ],
              [
                "Customer account",
                "Deleted after 3 years of inactivity (we warn you first), or earlier on your request"
              ],
              [
                "Analytics data",
                "Per our Google Analytics retention setting (14 months)"
              ]
            ]
          },
          "When a retention period ends we delete or anonymise the data, unless the law requires us to keep it longer."
        ]
      },
      {
        "id": "7",
        "heading": "7. The AI chat assistant",
        "body": [
          "Our website has a chat assistant powered by artificial intelligence from Anthropic. When you open it, we tell you clearly that you are chatting with an AI, not a human. It answers questions about our equipment, delivery and Athens. It cannot make bookings, confirm availability or give medical advice, and it does not make any decision that produces legal or similarly significant effects about you. A real person answers on WhatsApp.",
          "**What we store:** the text of your messages, the language, your browser's user-agent text, a salted one-way hash of your IP address (we use it only to limit abuse and cannot recover your IP from it), timestamps and technical usage counts.",
          "**Who sees it:** Anthropic processes the text of your messages on our behalf to produce the replies. Our team may read conversations to improve the service.",
          "**How long:** conversations are deleted automatically after 90 days.",
          "Please do not type health details, card numbers, passwords or ID numbers into the chat — the assistant does not need them and is instructed not to ask for them. If sensitive information is nevertheless sent, we do not use it for any purpose beyond answering you, and we delete conversations containing unnecessary sensitive information earlier than the standard 90 days, on review or on your request at info@movability.gr."
        ]
      },
      {
        "id": "8",
        "heading": "8. Cookies and similar technologies",
        "body": [
          "We use cookies and similar technologies that store or access information on your device. Google Analytics helps us understand how the site is used (pages visited, device type, approximate location). Its cookies are set only if you accept them in our cookie banner, where Accept and Reject are offered equally, and you can change your choice at any time.",
          "The site also keeps a few things in your browser's local storage so that it works: your language choice, your shopping cart, and whether you have closed the chat tip. These are needed to provide the features you asked for and are not used for tracking."
        ]
      },
      {
        "id": "9",
        "heading": "9. Your rights",
        "body": [
          "Under the GDPR you can ask us to:",
          [
            "give you a copy of your personal data (access)",
            "correct data that is wrong (rectification)",
            "delete your data (erasure), where the law allows",
            "limit how we use it (restriction)",
            "give you your data in a portable format (portability)",
            "stop using it for our legitimate interests, including the booking reminder and review request (objection)",
            "stop relying on your consent, for example for analytics cookies or health information you wrote (withdrawal)"
          ],
          "Write to info@movability.gr. We reply within one month. If you are not satisfied, you may lodge a complaint with the Hellenic Data Protection Authority (dpa.gr) or, where applicable, with the supervisory authority in the EU/EEA Member State of your habitual residence, place of work, or the place of the alleged infringement."
        ]
      },
      {
        "id": "10",
        "heading": "10. Security, children and changes",
        "body": [
          "**Security.** Connections to our site are encrypted. Access to bookings is limited to our staff, and the database enforces access rules. Card payments go through Stripe. Where required by applicable data-protection law, we will notify the competent supervisory authority and affected individuals of a personal data breach.",
          "**Children.** Bookings and customer accounts may only be created by persons aged 18 or over. Adults may rent equipment for a child in their care; any information about the child is processed only to fulfil that rental.",
          "**Changes.** If we change this policy we will update the date below and, for material changes, tell you on the website.",
          "This English text is provided for convenience; in case of any discrepancy, the Greek version prevails."
        ]
      }
    ]
  },
  "gr": {
    "metaTitle": "Πολιτική Απορρήτου | Movability",
    "metaDescription": "Πώς η ΚΟΪΝΗΣ ΙΚΕ συλλέγει, χρησιμοποιεί και διατηρεί τα προσωπικά σας δεδομένα κατά την ενοικίαση εξοπλισμού κινητικότητας στην Αθήνα.",
    "lastUpdatedLabel": "Τελευταία ενημέρωση",
    "pendingLabel": "Εκκρεμεί",
    "contactLine": "Ερωτήσεις για αυτήν την πολιτική; Στείλτε email στο",
    "title": "Πολιτική Απορρήτου",
    "lastUpdated": "2 Οκτωβρίου 2026",
    "intro": [
      "Το ελληνικό κείμενο είναι το αυθεντικό· η αγγλική έκδοση παρέχεται για διευκόλυνση."
    ],
    "sections": [
      {
        "id": "1",
        "heading": "1. Ποιοι είμαστε",
        "body": [
          "Η Movability (movability.gr) ενοικιάζει εξοπλισμό κινητικότητας στην Αθήνα. Την υπηρεσία λειτουργεί η ΚΟΪΝΗΣ ΙΚΕ, ΑΦΜ EL999050083, Υψηλάντου 22, 17778 Ταύρος, Αττική. Είμαστε ο υπεύθυνος επεξεργασίας των προσωπικών δεδομένων που περιγράφονται στην παρούσα πολιτική.",
          "Για κάθε ερώτημα ή αίτημα σχετικά με τα προσωπικά σας δεδομένα, γράψτε στο info@movability.gr.",
          "Η παρούσα πολιτική καλύπτει τον ιστότοπό μας, τις κρατήσεις, τους λογαριασμούς πελατών, τον βοηθό συνομιλίας με τεχνητή νοημοσύνη και την επικοινωνία μας μαζί σας μέσω email και WhatsApp."
        ]
      },
      {
        "id": "2",
        "heading": "2. Ποια προσωπικά δεδομένα συλλέγουμε",
        "body": [
          "Συλλέγουμε μόνο ό,τι χρειαζόμαστε για να σας ενοικιάσουμε εξοπλισμό, να τον παραδώσουμε και να απαντήσουμε στις ερωτήσεις σας.",
          {
            "headers": [
              "Όταν εσείς",
              "Τι συλλέγουμε"
            ],
            "rows": [
              [
                "Κάνετε κράτηση",
                "Όνομα, email, τηλέφωνο (και αριθμό WhatsApp), διεύθυνση παράδοσης ή όνομα ξενοδοχείου, ημερομηνίες ενοικίασης, ζώνη ώρας παράδοσης, σημειώσεις παράδοσης, τον εξοπλισμό, τα ποσά που καταβλήθηκαν και τυχόν ειδικές απαιτήσεις που επιλέγετε να γράψετε"
              ],
              [
                "Δημιουργείτε λογαριασμό (προαιρετικό)",
                "Όνομα, email, τηλέφωνο και κωδικό πρόσβασης (αποθηκεύεται μόνο ως μη αναστρέψιμο hash) ή το αναγνωριστικό σύνδεσης Google"
              ],
              [
                "Πληρώνετε",
                "Οι πληρωμές με κάρτα γίνονται μέσω Stripe. Δεν βλέπουμε και δεν αποθηκεύουμε ποτέ τον αριθμό της κάρτας σας. Κρατάμε την κατάσταση πληρωμής, τα ποσά και τα αναγνωριστικά πληρωμής Stripe"
              ],
              [
                "Επικοινωνείτε μαζί μας ή στέλνετε αίτημα συνεργασίας",
                "Όνομα, email, τηλέφωνο, θέμα και μήνυμα"
              ],
              [
                "Συνομιλείτε με τον βοηθό AI",
                "Τα μηνύματα που πληκτρολογείτε, τη γλώσσα, το user-agent του προγράμματος περιήγησης, ένα μη αναστρέψιμο salted hash της διεύθυνσης IP (όχι την ίδια τη διεύθυνση IP) και χρονοσημάνσεις"
              ],
              [
                "Μας στέλνετε μήνυμα στο WhatsApp ή τηλεφωνείτε",
                "Τον αριθμό σας και το περιεχόμενο της συνομιλίας"
              ],
              [
                "Περιηγείστε στον ιστότοπο",
                "Cookies και δεδομένα analytics, όπως περιγράφονται στην ενότητα 8"
              ]
            ]
          },
          "Σας στέλνουμε επίσης αυτοματοποιημένα email: επιβεβαιώσεις κράτησης, ένα αίτημα αξιολόγησης μετά την ενοικίαση και μία υπενθύμιση αν ξεκινήσετε κράτηση χωρίς να ολοκληρώσετε την πληρωμή.",
          "**Πληροφορίες υγείας.** Τα πεδία ειδικών απαιτήσεων και σημειώσεων παράδοσης είναι προαιρετικά πεδία ελεύθερου κειμένου. Δεν χρειάζεται να μας αναφέρετε διάγνωση — αρκεί να περιγράψετε τις λειτουργικές σας ανάγκες (π.χ. «πρόσβαση χωρίς σκαλιά», «στενές πόρτες») για να φέρουμε τον κατάλληλο εξοπλισμό. Αν επιλέξετε να δώσετε πληροφορίες για την υγεία ή την αναπηρία σας, ζητάμε τη ρητή συγκατάθεσή σας κατά την παροχή τους και τις επεξεργαζόμαστε αποκλειστικά για την οργάνωση και εκτέλεση της ενοικίασής σας. Δεν τις χρησιμοποιούμε ποτέ για εμπορικούς σκοπούς. Μπορείτε να ανακαλέσετε τη συγκατάθεσή σας οποτεδήποτε στο info@movability.gr· η ανάκληση δεν θίγει την επεξεργασία που έχει ήδη νομίμως πραγματοποιηθεί.",
          "Δεν πουλάμε προσωπικά δεδομένα."
        ]
      },
      {
        "id": "3",
        "heading": "3. Γιατί χρησιμοποιούμε τα δεδομένα σας και με ποια νομική βάση",
        "body": [
          {
            "headers": [
              "Σκοπός",
              "Νομική βάση (ΓΚΠΔ)"
            ],
            "rows": [
              [
                "Λήψη της κράτησης, παράδοση και παραλαβή του εξοπλισμού, είσπραξη πληρωμής, επιστροφή της εγγύησης",
                "Σύμβαση, άρθρο 6(1)(β)"
              ],
              [
                "Αποστολή επιβεβαιώσεων κράτησης και ενημερώσεων παράδοσης ή παραλαβής",
                "Σύμβαση, άρθρο 6(1)(β)"
              ],
              [
                "Δημιουργία και λειτουργία του προαιρετικού λογαριασμού σας (σύνδεση και ταυτοποίηση)",
                "Σύμβαση, άρθρο 6(1)(β)"
              ],
              [
                "Απάντηση σε ερωτήσεις και αιτήματα συνεργασίας μέσω φόρμας, email, WhatsApp, τηλεφώνου ή chat",
                "Σύμβαση (αν κάνετε κράτηση) ή το έννομο συμφέρον μας να απαντάμε σε όσους επικοινωνούν μαζί μας, άρθρο 6(1)(στ)"
              ],
              [
                "Τήρηση λογιστικών και φορολογικών αρχείων",
                "Έννομη υποχρέωση, άρθρο 6(1)(γ)"
              ],
              [
                "Μία υπενθύμιση για κράτηση που ξεκινήσατε χωρίς να ολοκληρώσετε",
                "Το έννομο συμφέρον μας να σας βοηθήσουμε να ολοκληρώσετε την κράτηση που ξεκινήσατε, άρθρο 6(1)(στ), εφόσον επιτρέπεται από την εφαρμοστέα νομοθεσία ηλεκτρονικών επικοινωνιών. Κάθε τέτοιο email περιέχει δυνατότητα εξαίρεσης και μπορείτε να αντιταχθείτε οποτεδήποτε"
              ],
              [
                "Αίτημα αξιολόγησης μετά την ενοικίαση",
                "Το έννομο συμφέρον μας να κατανοούμε και να βελτιώνουμε την υπηρεσία μας, άρθρο 6(1)(στ). Κάθε τέτοιο email περιέχει δυνατότητα εξαίρεσης και μπορείτε να αντιταχθείτε οποτεδήποτε"
              ],
              [
                "Λειτουργία του βοηθού συνομιλίας AI",
                "Το έννομο συμφέρον μας να απαντάμε στις ερωτήσεις των επισκεπτών και να αποτρέπουμε δόλια ή καταχρηστική χρήση του ιστοτόπου, άρθρο 6(1)(στ)"
              ],
              [
                "Ασφάλεια του ιστοτόπου και πρόληψη απάτης",
                "Το έννομο συμφέρον μας να αποτρέπουμε δόλια ή καταχρηστική χρήση του ιστοτόπου, άρθρο 6(1)(στ)"
              ],
              [
                "Cookies analytics",
                "Η συγκατάθεσή σας, άρθρο 6(1)(α)"
              ],
              [
                "Πληροφορίες υγείας που επιλέγετε να δώσετε",
                "Η ρητή συγκατάθεσή σας, άρθρο 9(2)(α)"
              ]
            ]
          }
        ]
      },
      {
        "id": "4",
        "heading": "4. Με ποιους τα μοιραζόμαστε",
        "body": [
          "Μοιραζόμαστε προσωπικά δεδομένα με τους παρόχους υπηρεσιών και τους λοιπούς αποδέκτες που αναφέρονται παρακάτω. Ανάλογα με την υπηρεσία και την πράξη επεξεργασίας, ενεργούν είτε ως εκτελούντες την επεξεργασία βάσει των οδηγιών μας είτε ως αυτοτελείς υπεύθυνοι επεξεργασίας. Η ομάδα παραδόσεων και το προσωπικό μας βλέπουν μόνο ό,τι χρειάζονται (όνομα, τηλέφωνο, διεύθυνση, εξοπλισμό).",
          {
            "headers": [
              "Πάροχος",
              "Τι κάνει για εμάς",
              "Δεδομένα σας που χειρίζεται"
            ],
            "rows": [
              [
                "Supabase",
                "Βάση δεδομένων, σύνδεση, αποθήκευση αρχείων και server functions",
                "Κρατήσεις, λογαριασμοί, αιτήματα, συνομιλίες chat"
              ],
              [
                "Vercel",
                "Φιλοξενία του ιστοτόπου",
                "Τεχνικά δεδομένα αιτημάτων"
              ],
              [
                "Stripe",
                "Πληρωμές με κάρτα",
                "Στοιχεία πληρωμής, όνομα, email, ποσό"
              ],
              [
                "Resend",
                "Αποστολή των email μας",
                "Διεύθυνση email, όνομα, περιεχόμενο email"
              ],
              [
                "Google",
                "Analytics (με τη συγκατάθεσή σας), σύνδεση Google",
                "Δεδομένα analytics, αναγνωριστικό σύνδεσης"
              ],
              [
                "Anthropic",
                "Παρέχει το μοντέλο AI του βοηθού συνομιλίας",
                "Το κείμενο των μηνυμάτων σας στο chat"
              ],
              [
                "WhatsApp (Meta)",
                "Μηνύματα, όταν επιλέγετε να μας γράψετε",
                "Ο αριθμός σας και η συνομιλία"
              ]
            ]
          },
          "Ενδέχεται επίσης να γνωστοποιήσουμε δεδομένα στον λογιστή μας και σε αρχές όπου το απαιτεί ο νόμος.",
          "Αν δημοσιεύσετε αξιολόγηση στο Google, αυτή δημοσιεύεται από την Google βάσει της δικής της πολιτικής, όχι της δικής μας."
        ]
      },
      {
        "id": "5",
        "heading": "5. Διαβιβάσεις εκτός ΕΕ/ΕΟΧ",
        "body": [
          "Ορισμένοι από τους παρόχους μας εδρεύουν στις ΗΠΑ ή επεξεργάζονται δεδομένα εκεί. Όταν τα δεδομένα σας εξέρχονται από την ΕΕ/ΕΟΧ, βασιζόμαστε σε απόφαση επάρκειας της ΕΕ (όπως το Πλαίσιο Προστασίας Δεδομένων ΕΕ–ΗΠΑ για πιστοποιημένους παρόχους) ή στις Τυποποιημένες Συμβατικές Ρήτρες. Μπορείτε να ζητήσετε αντίγραφο των εγγυήσεων στο info@movability.gr."
        ]
      },
      {
        "id": "6",
        "heading": "6. Για πόσο χρόνο κρατάμε τα δεδομένα",
        "body": [
          {
            "headers": [
              "Δεδομένα",
              "Διάρκεια"
            ],
            "rows": [
              [
                "Συνομιλίες με τον βοηθό AI",
                "90 ημέρες, κατόπιν αυτόματη διαγραφή"
              ],
              [
                "Στοιχεία κρατήσεων και πληρωμών που απαιτούνται για λογιστικούς και φορολογικούς σκοπούς",
                "5 έτη από το τέλος του έτους στο οποίο γεννάται η σχετική φορολογική υποχρέωση, ή περισσότερο όσο παραμένει ανοιχτή η προθεσμία ελέγχου, εκκρεμεί έλεγχος ή διαφορά, ή το απαιτεί άλλος κανόνας δικαίου"
              ],
              [
                "Λειτουργικά στοιχεία κράτησης (σημειώσεις παράδοσης, διευθύνσεις, ζώνες ώρας)",
                "2 έτη μετά τη λήξη της ενοικίασης"
              ],
              [
                "Πληροφορίες υγείας που δώσατε για κράτηση",
                "60 ημέρες μετά τη λήξη της ενοικίασης"
              ],
              [
                "Αιτήματα επικοινωνίας και συνεργασίας",
                "2 έτη"
              ],
              [
                "Κρατήσεις που ξεκίνησαν αλλά δεν πληρώθηκαν",
                "6 μήνες"
              ],
              [
                "Λογαριασμός πελάτη",
                "Διαγραφή μετά από 3 έτη αδράνειας (με προηγούμενη ειδοποίηση), ή νωρίτερα κατόπιν αιτήματός σας"
              ],
              [
                "Δεδομένα analytics",
                "Σύμφωνα με τη ρύθμιση διατήρησης του Google Analytics (14 μήνες)"
              ]
            ]
          },
          "Όταν λήξει μια περίοδος διατήρησης, διαγράφουμε ή ανωνυμοποιούμε τα δεδομένα, εκτός αν ο νόμος απαιτεί να τα κρατήσουμε περισσότερο."
        ]
      },
      {
        "id": "7",
        "heading": "7. Ο βοηθός συνομιλίας AI",
        "body": [
          "Ο ιστότοπός μας διαθέτει βοηθό συνομιλίας που λειτουργεί με τεχνητή νοημοσύνη της Anthropic. Όταν τον ανοίγετε, σας ενημερώνουμε με σαφήνεια ότι συνομιλείτε με AI και όχι με άνθρωπο. Απαντά σε ερωτήσεις για τον εξοπλισμό μας, την παράδοση και την Αθήνα. Δεν μπορεί να κάνει κρατήσεις, να επιβεβαιώσει διαθεσιμότητα ή να δώσει ιατρικές συμβουλές, και δεν λαμβάνει καμία απόφαση που παράγει έννομα ή παρόμοια σημαντικά αποτελέσματα για εσάς. Στο WhatsApp απαντά πραγματικός άνθρωπος.",
          "**Τι αποθηκεύουμε:** το κείμενο των μηνυμάτων σας, τη γλώσσα, το user-agent του προγράμματος περιήγησης, ένα μη αναστρέψιμο salted hash της διεύθυνσης IP (το χρησιμοποιούμε μόνο για περιορισμό κατάχρησης και δεν μπορούμε να ανακτήσουμε την IP από αυτό), χρονοσημάνσεις και τεχνικούς μετρητές χρήσης.",
          "**Ποιος τα βλέπει:** Η Anthropic επεξεργάζεται το κείμενο των μηνυμάτων σας για λογαριασμό μας ώστε να παράγει τις απαντήσεις. Η ομάδα μας μπορεί να διαβάζει συνομιλίες για τη βελτίωση της υπηρεσίας.",
          "**Για πόσο:** οι συνομιλίες διαγράφονται αυτόματα μετά από 90 ημέρες.",
          "Παρακαλούμε μην πληκτρολογείτε στο chat στοιχεία υγείας, αριθμούς καρτών, κωδικούς ή αριθμούς ταυτότητας — ο βοηθός δεν τα χρειάζεται και έχει οδηγίες να μην τα ζητά. Αν παρ' όλα αυτά σταλούν ευαίσθητες πληροφορίες, δεν τις χρησιμοποιούμε για κανέναν σκοπό πέρα από την απάντηση προς εσάς και διαγράφουμε συνομιλίες με μη αναγκαίες ευαίσθητες πληροφορίες νωρίτερα από τις 90 ημέρες, κατόπιν ελέγχου ή αιτήματός σας στο info@movability.gr."
        ]
      },
      {
        "id": "8",
        "heading": "8. Cookies και παρόμοιες τεχνολογίες",
        "body": [
          "Χρησιμοποιούμε cookies και παρόμοιες τεχνολογίες που αποθηκεύουν ή αποκτούν πρόσβαση σε πληροφορίες στη συσκευή σας. Το Google Analytics μάς βοηθά να κατανοούμε πώς χρησιμοποιείται ο ιστότοπος (σελίδες που επισκέπτεστε, τύπος συσκευής, κατά προσέγγιση τοποθεσία). Τα cookies του τοποθετούνται μόνο αν τα αποδεχθείτε στο banner cookies, όπου η Αποδοχή και η Απόρριψη προσφέρονται ισότιμα, και μπορείτε να αλλάξετε την επιλογή σας οποτεδήποτε.",
          "Ο ιστότοπος αποθηκεύει επίσης λίγα στοιχεία στο local storage του προγράμματος περιήγησης για να λειτουργεί: τη γλώσσα που επιλέξατε, το καλάθι σας και το αν έχετε κλείσει την υπόδειξη του chat. Αυτά είναι αναγκαία για τις λειτουργίες που ζητήσατε και δεν χρησιμοποιούνται για παρακολούθηση."
        ]
      },
      {
        "id": "9",
        "heading": "9. Τα δικαιώματά σας",
        "body": [
          "Βάσει του ΓΚΠΔ μπορείτε να μας ζητήσετε:",
          [
            "αντίγραφο των προσωπικών σας δεδομένων (δικαίωμα πρόσβασης)",
            "διόρθωση ανακριβών δεδομένων (δικαίωμα διόρθωσης)",
            "διαγραφή των δεδομένων σας, όπου το επιτρέπει ο νόμος (δικαίωμα διαγραφής)",
            "περιορισμό της επεξεργασίας (δικαίωμα περιορισμού)",
            "τα δεδομένα σας σε φορητή μορφή (δικαίωμα φορητότητας)",
            "να σταματήσουμε την επεξεργασία που βασίζεται σε έννομο συμφέρον, συμπεριλαμβανομένης της υπενθύμισης κράτησης και του αιτήματος αξιολόγησης (δικαίωμα εναντίωσης)",
            "να μη βασιζόμαστε πλέον στη συγκατάθεσή σας, για παράδειγμα για cookies analytics ή για πληροφορίες υγείας που γράψατε (ανάκληση συγκατάθεσης)"
          ],
          "Γράψτε στο info@movability.gr. Απαντάμε εντός ενός μήνα. Αν δεν μείνετε ικανοποιημένοι, μπορείτε να υποβάλετε καταγγελία στην Αρχή Προστασίας Δεδομένων Προσωπικού Χαρακτήρα (dpa.gr) ή, κατά περίπτωση, στην εποπτική αρχή του κράτους μέλους ΕΕ/ΕΟΧ της συνήθους διαμονής σας, του τόπου εργασίας σας ή του τόπου της φερόμενης παράβασης."
        ]
      },
      {
        "id": "10",
        "heading": "10. Ασφάλεια, παιδιά και αλλαγές",
        "body": [
          "**Ασφάλεια.** Οι συνδέσεις στον ιστότοπό μας είναι κρυπτογραφημένες. Η πρόσβαση στις κρατήσεις περιορίζεται στο προσωπικό μας και η βάση δεδομένων επιβάλλει κανόνες πρόσβασης. Οι πληρωμές με κάρτα γίνονται μέσω Stripe. Όπου το απαιτεί η εφαρμοστέα νομοθεσία προστασίας δεδομένων, θα ενημερώσουμε την αρμόδια εποπτική αρχή και τα θιγόμενα πρόσωπα για τυχόν παραβίαση προσωπικών δεδομένων.",
          "**Παιδιά.** Κρατήσεις και λογαριασμοί πελατών επιτρέπονται μόνο σε πρόσωπα ηλικίας 18 ετών και άνω. Οι ενήλικες μπορούν να ενοικιάσουν εξοπλισμό για παιδί που φροντίζουν· τυχόν στοιχεία του παιδιού επεξεργάζονται μόνο για την εκτέλεση της συγκεκριμένης ενοικίασης.",
          "**Αλλαγές.** Αν τροποποιήσουμε την παρούσα πολιτική, θα ενημερώσουμε την παρακάτω ημερομηνία και, για ουσιώδεις αλλαγές, θα σας ενημερώσουμε μέσω του ιστοτόπου."
        ]
      }
    ]
  }
};
